development:
  adapter: postgresql
  encoding: unicode
  database: jugglejob_development
  pool: 5
  username: carlgoulding
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: juggljob_test
  pool: 5
  username: carlgoulding
  password: 